name: arotest
favicon: null
layout_spectrum: 0.7787550722714514
typography_spectrum: 0.24518612283281982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35880780941806734
  lightness: 0.33243915322236717
  saturation: 0.5564964476507157
  rhythmicContrast: 0.7985912461299449
purpose: []
