name: arotest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#36344b'
    - '#0098f9'
    - '#87c6f2'
    - '#fbfbe4'
    - '#ffaf65'
  brandStrength: 0.6875
  lightness: 0.33243915322236717
  saturation: 0.5564964476507157
  rhythmicContrast: 0.7985912461299449
purpose: []
