name: arotest
favicon: null
layout_spectrum: 0.10764
typography_spectrum: 0.10851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#151515'
    - '#000000'
    - '#111111'
    - '#0e0e0e'
  brandStrength: 1
  lightness: 0.33243915322236717
  saturation: 0.5564964476507157
  rhythmicContrast: 0.7985912461299449
purpose: []
